name: ✨ Feature Request
description: Suggest an idea for bobaland
title: "[FEATURE] <short description>"
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear and concise description of the feature you want.
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Rationale
      description: Why would this feature be useful to the users?
    validations:
      required: true
  - type: textarea
    id: implementation
    attributes:
      label: Potential Implementation
      description: How do you envision this feature being implemented? (Optional)
